# Generated by Django 5.2 on 2025-04-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(help_text='Plase Enter Your Text Here ', max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='Home',
        ),
    ]
