# Generated by Django 5.2 on 2025-04-12 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_article_delete_home'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Products',
        ),
    ]
