# Generated by Django 5.2 on 2025-04-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_title_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='none', help_text='عنوان دسته بندی', max_length=100),
        ),
    ]
