# Generated by Django 5.2 on 2025-04-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_category_title_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
    ]
