# Generated by Django 5.2 on 2025-05-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_is_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url_name',
            field=models.CharField(blank=True, help_text='این عنوان برای آدرس دهی دسته بندی ها استفاده میشود, پس از این اسم حتما باید در آدرس دهی استفاده کنید.', max_length=100, null=True),
        ),
    ]
